#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Holberton School'.
#
# Also, the script, configure a directive of the Nginx server
# to redirect to another page with 301 HTTP Code
#

#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
STR="Hello World!"
RED="\n\tlocation /rediect_me {\n\t\treturn 301 https://youtube.com; \n\t}\n"
FILE="/etc/nginx/states-available/default"
apt-get -y update
apt-get -y install ngnix
ufw allow 'Nginx HTTP'
echo "$STR" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $RED" "$FILE"
service nginx restart
