#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# When querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Holberton School'.
#
# Configures a directive of the Nginx server
# to redirect to another page with 301 HTTP Code
#
# Configures a custom 404 page that contains the string
# 'Ceci n'est pas une page'.
#

STR="Hello World!"

RED="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com;\n\t}\n"
FILE="/etc/nginx/sites-available/default"

ERR_FILE="/usr/share/nginx/html/404error.html"
ERR_STR="Ceci n'est pas une page"
ERR_DIR="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "$STR" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $RED" "$FILE"

echo "$ERR_STR" > "$ERR_FILE"
sed -i "37i\ $ERR_DIR" "$FILE"

service nginx restart
