#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times,
# but for the 9th iteration, displays Holberton School
# and then Hi on a new line.
i=1

while [ $i -lt "10" ]
do
    echo "Best School"

    if [ $i -eq "9" ]
    then
        echo "Hi"
        echo "Best School"
    fi

    ((i += 1))
done