#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01.
# except for tcp ports 22, 443, 80
apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
